pref("extensions.zotero.__addonRef__.enable", true);
pref("extensions.zotero.__addonRef__.enable1", false);
pref("extensions.zotero.__addonRef__.input", "This is input");
// 期刊缩写
pref("extensions.zotero.__addonRef__.add.update", false);
pref("extensions.zotero.__addonRef__.update.abbr", true);
pref("extensions.zotero.__addonRef__.update.abbr.dot", true);
pref("extensions.zotero.__addonRef__.en.abbr", true);
pref("extensions.zotero.__addonRef__.ch.abbr", true);

// 学校期刊分类
pref("extensions.zotero.__addonRef__.swufe", false);
pref("extensions.zotero.__addonRef__.cufe", false);
pref("extensions.zotero.__addonRef__.uibe", false);
pref("extensions.zotero.__addonRef__.sdufe", false);
pref("extensions.zotero.__addonRef__.xdu", false);
pref("extensions.zotero.__addonRef__.swjtu", false);
pref("extensions.zotero.__addonRef__.ruc", false);
pref("extensions.zotero.__addonRef__.xmu", false);
pref("extensions.zotero.__addonRef__.sjtu", false);
pref("extensions.zotero.__addonRef__.fdu", false);
pref("extensions.zotero.__addonRef__.hhu", false);
pref("extensions.zotero.__addonRef__.scu", false);
pref("extensions.zotero.__addonRef__.cqu", false);
pref("extensions.zotero.__addonRef__.nju", false);
pref("extensions.zotero.__addonRef__.xju", false);
pref("extensions.zotero.__addonRef__.cug", false);
pref("extensions.zotero.__addonRef__.cju", false);
pref("extensions.zotero.__addonRef__.zju", false);
pref("extensions.zotero.__addonRef__.njau.core", true);
pref("extensions.zotero.__addonRef__.njau.high.quality", true);
// 自定义数据集
pref("extensions.zotero.__addonRef__.clsci", false);
pref("extensions.zotero.__addonRef__.ami", false);
pref("extensions.zotero.__addonRef__.nssf", false);


// 影响因子
pref("extensions.zotero.__addonRef__.jcr.qu", true);
pref("extensions.zotero.__addonRef__.basic", false);
pref("extensions.zotero.__addonRef__.updated", true);
pref("extensions.zotero.__addonRef__.sci.if", true);
pref("extensions.zotero.__addonRef__.sci.if5", true);
pref("extensions.zotero.__addonRef__.ei", true);
pref("extensions.zotero.__addonRef__.chjcscd", true);
pref("extensions.zotero.__addonRef__.pku.core", true);
pref("extensions.zotero.__addonRef__.nju.core", true);
pref("extensions.zotero.__addonRef__.sci.core", true);
pref("extensions.zotero.__addonRef__.ssci", true);
pref("extensions.zotero.__addonRef__.ajg", true);
pref("extensions.zotero.__addonRef__.utd24", true);
pref("extensions.zotero.__addonRef__.ft50", true);
pref("extensions.zotero.__addonRef__.ccf", true);
pref("extensions.zotero.__addonRef__.fms", true);
pref("extensions.zotero.__addonRef__.jci", true);
pref("extensions.zotero.__addonRef__.ahci", true);
pref("extensions.zotero.__addonRef__.com.if", true);
pref("extensions.zotero.__addonRef__.agg.if", true);
pref("extensions.zotero.__addonRef__.summary", false);
pref("extensions.zotero.__addonRef__.bold.star", true);
pref("extensions.zotero.__addonRef__.remove.bold", true);
pref("extensions.zotero.__addonRef__.remove.star", true);
pref("extensions.zotero.__addonRef__.remove.bold.star", true);
pref("extensions.zotero.__addonRef__.chang.author.case", true);
pref("extensions.zotero.__addonRef__.swap.author", true);
pref("extensions.zotero.__addonRef__.chang.title", true);
pref("extensions.zotero.__addonRef__.chang.pub.title", true);
pref("extensions.zotero.__addonRef__.chang.pub.title.case", true);
pref("extensions.zotero.__addonRef__.item.title.find.replace", true);
pref("extensions.zotero.__addonRef__.show.profile.dir", true);
pref("extensions.zotero.__addonRef__.show.data.dir", true);
pref("extensions.zotero.__addonRef__.sep1", true);
pref("extensions.zotero.__addonRef__.sep2", true);
